// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/VitalyCoder/todo_go/ent/predicate"
	"github.com/VitalyCoder/todo_go/ent/todo"
	"github.com/VitalyCoder/todo_go/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TodoUpdate is the builder for updating Todo entities.
type TodoUpdate struct {
	config
	hooks    []Hook
	mutation *TodoMutation
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdate) Where(ps ...predicate.Todo) *TodoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *TodoUpdate) SetVersion(v int) *TodoUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableVersion(v *int) *TodoUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *TodoUpdate) AddVersion(v int) *TodoUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TodoUpdate) SetTitle(v string) *TodoUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableTitle(v *string) *TodoUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TodoUpdate) SetDescription(v string) *TodoUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableDescription(v *string) *TodoUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *TodoUpdate) SetCompleted(v bool) *TodoUpdate {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableCompleted(v *bool) *TodoUpdate {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TodoUpdate) SetUpdatedAt(v time.Time) *TodoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *TodoUpdate) SetAuthorID(v uuid.UUID) *TodoUpdate {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableAuthorID(v *uuid.UUID) *TodoUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *TodoUpdate) SetAuthor(v *User) *TodoUpdate {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdate) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *TodoUpdate) ClearAuthor() *TodoUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TodoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TodoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TodoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := todo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := todo.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Todo.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := todo.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Todo.description": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.author"`)
	}
	return nil
}

func (_u *TodoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(todo.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(todo.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(todo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(todo.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(todo.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.AuthorTable,
			Columns: []string{todo.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.AuthorTable,
			Columns: []string{todo.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TodoUpdateOne is the builder for updating a single Todo entity.
type TodoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TodoMutation
}

// SetVersion sets the "version" field.
func (_u *TodoUpdateOne) SetVersion(v int) *TodoUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableVersion(v *int) *TodoUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *TodoUpdateOne) AddVersion(v int) *TodoUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TodoUpdateOne) SetTitle(v string) *TodoUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableTitle(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TodoUpdateOne) SetDescription(v string) *TodoUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableDescription(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *TodoUpdateOne) SetCompleted(v bool) *TodoUpdateOne {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableCompleted(v *bool) *TodoUpdateOne {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TodoUpdateOne) SetUpdatedAt(v time.Time) *TodoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *TodoUpdateOne) SetAuthorID(v uuid.UUID) *TodoUpdateOne {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableAuthorID(v *uuid.UUID) *TodoUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *TodoUpdateOne) SetAuthor(v *User) *TodoUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdateOne) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *TodoUpdateOne) ClearAuthor() *TodoUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdateOne) Where(ps ...predicate.Todo) *TodoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TodoUpdateOne) Select(field string, fields ...string) *TodoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Todo entity.
func (_u *TodoUpdateOne) Save(ctx context.Context) (*Todo, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdateOne) SaveX(ctx context.Context) *Todo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TodoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TodoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := todo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := todo.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Todo.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := todo.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Todo.description": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.author"`)
	}
	return nil
}

func (_u *TodoUpdateOne) sqlSave(ctx context.Context) (_node *Todo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Todo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todo.FieldID)
		for _, f := range fields {
			if !todo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(todo.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(todo.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(todo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(todo.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(todo.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.AuthorTable,
			Columns: []string{todo.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.AuthorTable,
			Columns: []string{todo.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Todo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
