version: "3.7"

services:
  todoapp-postgres:
    container_name: todoapp-postgres
    image: postgres:18.1-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - ${PROJECT_ROOT}/out/postgres_data:/var/lib/postgresql
    networks:
      - main

volumes:
  postgres_data:

networks:
  main:
